language: php
dist: trusty

php:
  - 7.2
  - 7.3

matrix:
  fast_finish: true

branches:
  only:
    - master

env:
  - COMPOSER_OPTS="--no-interaction --prefer-dist --no-suggest"

install:
  - travis_retry composer update $COMPOSER_OPTS

script:
  - ./vendor/bin/phpunit -c phpunit.ci.xml --testsuite Unit

notifications:
  email:
    recipients:
      - codedungeon@gmail.com
    on_success: always # default: change
    on_failure: always # default: always

after_success:
- bash <(curl -s https://codecov.io/bash)